### ISSUE TITLE
zsh: command not found: npm

### ISSUE THREAD

**Issue by AlexDenisov** [jankuca/swm#1]
I know how to fix the problem, but some people don't use NodeJS and, probably, don't want to install it on their machines.
Is there another way to install swm?

**Comment by jankuca** [comment]
It is right below the `npm` command in the README. Please try to read more carefully.

```
curl "https://raw.github.com/jankuca/swm/master/install.sh" | bash
```

(Or does the install script not work for you?)

**Comment by AlexDenisov** [comment]
Yes, you're right, I missed that point.
Maybe makes sense to exchange this options...

**Comment by jankuca** [comment]
Great, I hope you find this useful.

I'm actually going to remove the npm way altogether.
